# -*- coding: utf-8 -*-
"""Descriptive_Statistics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NHB-AfeK3w9VSfTDQQxMa0MDhZGtJ0c9
"""

pip install pandas

from google.colab import files

uploaded = files.upload()

import pandas as pd

columns = [
    "SepalLengthCm",
    "SepalWidthCm",
    "PetalLengthCm",
    "PetalWidthCm",
    "Species"
]

df = pd.read_csv("iris.data.csv", header=None, names=columns)


for column in columns[:-1]: # Exclude 'Species' from statistical analysis
    print("\n", column)
    print("Mean:", df[column].mean())
    print("Median:", df[column].median())
    print("Mode:", df[column].mode().iloc[0])
    print("Standard Deviation:", df[column].std())
    print("25th Percentile:", df[column].quantile(0.25))
    print("50th Percentile:", df[column].quantile(0.50))
    print("75th Percentile:", df[column].quantile(0.75))

import pandas as pd

# Define all column names for the CSV file
all_columns = [
    "SepalLengthCm",
    "SepalWidthCm",
    "PetalLengthCm",
    "PetalWidthCm",
    "Species"
]

# Read the CSV with no header and assign the defined column names
df = pd.read_csv("iris.data.csv", header=None, names=all_columns)

# Define columns for statistical description (excluding 'Species')
columns_for_describe = [
    "SepalLengthCm",
    "SepalWidthCm",
    "PetalLengthCm",
    "PetalWidthCm"
]

print(df[columns_for_describe].describe())

print(df[columns].mode())